---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      dockerfile: ./dockerfiles/centos7
      privileged: true
      run_command: /usr/sbin/init # Start systemd as root process
      use_sudo: false
    run_list:
      - recipe[jenkins::kitchen]
      - recipe[jenkins::packages]

  - name: centos-6
    driver_config:
      dockerfile: ./dockerfiles/centos6
      privileged: true
      use_sudo: false
    run_list:
      - recipe[jenkins::packages]

suites:
  - name: default
    run_list:
      - recipe[jenkins::default]
    verifier:
      inspec_tests:
        - test/recipes
    excludes:
      - centos-6
    attributes:

  - name: iti
    run_list:
    #  - recipe[jenkins::iti]
    verifier:
      inspec_tests:
        - test/recipes/iti_test.rb
    attributes:
