---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      dockerfile: ./dockerfiles/centos7
      privileged: true
      run_command: /usr/sbin/init # Start systemd as root process
      use_sudo: false

suites:
  - name: default
    run_list:
      - recipe[iptables::default]
      - recipe[jenkins::kitchen]
      - recipe[jenkins::default]
      - recipe[jenkins::packages]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
